name: build
on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: windows-latest
    steps:
      - id: step1
        run: echo 'build job-> step 1'
  gated-via-environment:
    runs-on: windows-latest
    environment : prod-gate
    steps:
      - id: step1
        run: echo 'gated job -> step 1'